# SITE CONFIGURATION
title: Lab Exam # your site title
author: GitHub User # You :P
description: > # Meta description of Homepage
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/labexam" # the subpath of your site, e.g. /blog
url: "https://janczizikow.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Setayesh
  links:
    - https://twitter.com/Setayesh
    - https://www.facebook.com/Setayesh
    - https://www.linkedin.com/in/Setayesh
    - https://plus.google.com/Setayesh
    - https://github.com/Setayesh
    - https://keybase.io/Setayesh

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}Courses
  - {name: 'Contact', link: '/contact'}
  - {name: 'Academic Calendar', link: 'http://www.iust.ac.ir/files/education/files/_%D9%85%D8%B5%D9%88%D8%A8_%D8%AA%D8%B1%D9%85__4021_-_%D8%A7%D8%B9%D9%85%D8%A7%D9%84_%D8%AA%D8%BA%DB%8C%DB%8C%D8%B1%D8%A7%D8%AA_24_%D9%85%D8%B1%D8%AF%D8%A7%D8%AF_1402_2(1).pdf'}
  - {name: 'Courses', link: '/Courses'}


tagline: >
  Modern Jekyll theme focused on speed performance &amp; SEO best practices

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: Setayesh.baghaee@gmail.com # email for form submission

twitter_username: Setayesh # replace with your_twitter_username or comment to remove link from footer
github_username:  Setayeshbaghaee # replace with your_github_username or comment to remove link from footer
instagram_username: Setayesh # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: Setayesh # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
